// Type definitions for jquery-lang-js module 4.0.0
// Project: https://github.com/Irrelon/jquery-lang-js
// Definitions by: Claudio Schilling <https://github.com/rbfowler9lfc>

/// <reference types="jquery" />

declare class Lang
{
	constructor();

	/**
	 * Initialise the library with the library options.
	 * @param {Object} options The options to init the library with.
	 * See the readme.md for the details of the options available.
	 */
	init(options : Lang.InitOptions) : void;

	/**
	 * Defines a language pack that can be dynamically loaded and the
	 * path to use when doing so.
	 * @param {String} lang The language two-letter iso-code.
	 * @param {String} path The path to the language pack js file.
	 */
	dynamic(lang : string, path : string) : void;

	/**
	 * Loads a new language pack for the given language.
	 * @param {string} lang The language to load the pack for.
	 * @param {Function=} callback Optional callback when the file has loaded.
	 */
	loadPack(lang : string, callback ?: (error : boolean) => void) : void;

	/**
	 * Call this to change the current language on the page.
	 * @param {String} lang The new two-letter language code to change to.
	 * @param {String=} selector Optional selector to find language-based
	 * elements for updating.
	 * @param {Function=} callback Optional callback function that will be
	 * called once the language change has been successfully processed. This
	 * is especially useful if you are using dynamic language pack loading
	 * since you will get a callback once it has been loaded and changed.
	 * Your callback will be passed three arguments, a boolean to denote if
	 * there was an error (true if error), the second will be the language
	 * you passed in the change call (the lang argument) and the third will
	 * be the selector used in the change update.
	 */
	change<T extends Lang.SelectorInput>(lang : string, selector ?: T, callback ?: (error : boolean, newLang : string, selector : T) => void) : void;

	/**
	 * Translates text from the default language into the passed language.
	 * @param {String} text The text to translate.
	 * @param {String} lang The two-letter language code to translate to.
	 */
	translate(text : string, lang ?: string, data ?: string | number | unknown[] | Record<string, unknown>) : string;

	getLangDataFromElement(elem : JQuery<HTMLElement>) : string;
	getDataAtPath(obj : Record<string, unknown>, path : string | string[], defaultval ?: string) : string | number;
	beforeUpdate(currentlang : string, newLang : string) : void;
	afterUpdate(currentlang : string, newLang : string) : void;
	refresh() : void;

	/**
	 * Object that holds the language packs.
	 */
	private pack : Record<string, unknown>;

	/**
	 * Array of translatable attributes to check for on elements.
	 */
	private attrList : string[];

	private _start(selector);
	private _processElement(elem);
	private _storeAttribs(elem);
	private _storeContent(elem);
	private _getTextNodes(elem);
	private _setTextNodes(elem, nodes, lang, data);
	private _translateAttribs(elem, lang, data);
	private _translateContent(elem, lang, data);
	private _translateElement(elem, lang, data);
	private _parseTemplate(str, data);
	private _regexMatch(text, lang);
	private _mutation(context, method, args);
}

export = Lang;

declare namespace Lang
{
	type SelectorInput = JQuery.htmlString | JQuery.Selector | Element[] | JQuery<unknown> | Element | JQuery.PlainObject<unknown>;

	interface CookiesOptions
	{
		/** Overrides the default cookie name to something else. The default is `"langCookie"`. */
		name ?: string;
		/** Sets the cookie expiry interval in days. The default is `365`. */
		expiry ?: number;
		/** Overrides the default cookie path to something else. The default is `"/"`. */
		path ?: string;
	}

	interface InitOptions
	{
		/** The default language of the page / app. */
		defaultLang : string;

		/** The current language to set the page to. */
		currentLang ?: string;

		/** This object is only required if you want to override the default settings for cookies. */
		cookie ?: Lang.CookiesOptions;

		/**
		 * If true, cookies will override the "currentLang" option if the
		 * cookie is set. You usually shouldn't need to specify this option
		 * at all unless your JavaScript lang.init() method is being
		 * dynamically generated by PHP or other server-side processor.
		 */
		allowCookieOverride ?: true;
	}
}
