jquery_lang_js.prototype.lang.en = {
	'property_search':'Property Search',
	'location':'Location',
	'budget':'Budget',
	'min_beds':'Min Beds',
	'property_type':'Property Type',
	'added_in':'Added In',
	'show_all':'Show All',
	'house':'House',
	'town_house':'Town House',
	'apartment':'Apartment',
	'condominium':'Condominium',
	'commercial':'Commercial',
	'office':'Office',
	'storage':'Storage',
	'land':'Land',
	'anytime':'Anytime',
	'last_24_hours':'Last 24 Hours',
	'last_3_days':'Last 3 Days',
	'last_week':'Last Week',
	'last_month':'Last Month',
	'loading':'Loading',
	'my_saved_searches':'My Saved Searches',
	'my_listings':'My Listings',
	'my_analytics':'My Analytics',
	'search_buy':'Search Buy',
	'search_rent':'Search rent',
	'create_new_listing':'Create New Listing',
	'view_my_account':'View My Account',
	'property_listing_details':'Property Listing Details',
	'listing_type':'Listing Type',
	'sell':'Sell',
	'let':'let',
	'lease':'Lease',
	'floors':'Floors',
	'rooms_total':'Rooms Total',
	'bedrooms':'Bedrooms',
	'bathrooms':'Bathrooms',
	'kitchens':'Kitchens',
	'property_price_and_terms':'Property Price and Terms',
	'price':'Price',
	'term':'Term',
	'freehold':'Freehold',
	'leasehold':'Leasehold',
	'possession':'Possession',
	'onward_chain':'Onward Chain',
	'vacant_possession':'Vacant Possession',
	'property_location':'Property Location',
	'country':'Country',
	'post_zip_code':'Post/Zip Code',
	'no':'No.',
	'road_name':'Road Name',
	'county_province':'County?Province',
	'town_city':'Town/City',
	'lease_years_remaining':'Lease Years Remaining',
	'day':'Day',
	'week':'Week',
	'month':'Month',
	'quarter':'Quarter',
	'year':'year',
	'submit_your_listing':'Submit Your Listing',
	'upload_image':'Upload Image',
	'finish':'Finish',
	'search':'Search',
	'search_ellipsis':'Search...',
	'property_description':'Property Description',
	'synopsis':'Synopsis',
	'full_description':'Full Description',
	'property_photos':'Property Photos',
}
